# Pre-commit configuration for Plataforma NXT Backend
# Install with: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # ================================
  # General checks
  # ================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-json
      - id: check-xml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: debug-statements
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']

  # ================================
  # Python code formatting
  # ================================
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.11
        args: ['--line-length=88']

  # ================================
  # Python import sorting
  # ================================
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=88']

  # ================================
  # Python linting
  # ================================
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [
          '--max-line-length=88',
          '--extend-ignore=E203,W503',
          '--exclude=migrations,__pycache__,.git,build,dist,.venv'
        ]
        additional_dependencies: [
          flake8-docstrings,
          flake8-import-order,
          flake8-bugbear,
          flake8-comprehensions,
          flake8-simplify,
        ]

  # ================================
  # Type checking
  # ================================
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies: [
          types-redis,
          types-python-dateutil,
          types-requests,
          sqlalchemy[mypy],
          pydantic
        ]
        args: [
          '--ignore-missing-imports',
          '--python-version=3.11',
          '--check-untyped-defs',
          '--disallow-untyped-defs',
          '--no-implicit-optional',
          '--warn-return-any',
          '--warn-unused-ignores'
        ]

  # ================================
  # Security checks
  # ================================
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-r', 'app/', '-f', 'json']
        exclude: ^tests/

  # ================================
  # Dependency security
  # ================================
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check

  # ================================
  # Documentation
  # ================================
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ['--convention=google', '--add-ignore=D100,D104']

  # ================================
  # Secrets detection
  # ================================
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

# ================================
# Configuration
# ================================
default_language_version:
  python: python3.11

default_stages: [commit]

# Exclude certain files/directories
exclude: |
  (?x)^(
    migrations/versions/.*\.py|
    .*\.min\.js|
    .*\.min\.css|
    node_modules/.*|
    \.git/.*|
    \.venv/.*|
    build/.*|
    dist/.*|
    __pycache__/.*
  )$

# Fail fast - stop on first failure
fail_fast: false

# Show diff when hooks modify files
default_install_hook_types: [pre-commit, pre-push]