# ==============================================================================
# Kubernetes Secrets for Plataforma FastAPI Backend
# IMPORTANT: Replace all placeholder values with actual secrets before deployment
# ==============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
  namespace: plataforma-fastapi
  labels:
    app: plataforma-fastapi
    component: secrets
type: Opaque
data:
  # Application secrets (base64 encoded)
  # Generate with: echo -n 'your-secret-here' | base64
  SECRET_KEY: your-secret-key-base64-encoded-here
  JWT_SECRET_KEY: your-jwt-secret-key-base64-encoded-here
  SESSION_SECRET_KEY: your-session-secret-key-base64-encoded-here
  
  # External service keys
  SUPABASE_URL: your-supabase-url-base64-encoded-here
  SUPABASE_ANON_KEY: your-supabase-anon-key-base64-encoded-here
  SUPABASE_SERVICE_KEY: your-supabase-service-key-base64-encoded-here
  
  # Monitoring secrets
  SENTRY_DSN: your-sentry-dsn-base64-encoded-here
  GRAFANA_ADMIN_PASSWORD: your-grafana-password-base64-encoded-here

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: plataforma-fastapi
  labels:
    app: plataforma-fastapi
    component: database
type: Opaque
data:
  # PostgreSQL secrets (base64 encoded)
  POSTGRES_PASSWORD: your-postgres-password-base64-encoded-here
  POSTGRES_REPLICATION_PASSWORD: your-replication-password-base64-encoded-here

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: plataforma-fastapi
  labels:
    app: plataforma-fastapi
    component: cache
type: Opaque
data:
  # Redis secrets (base64 encoded)
  REDIS_PASSWORD: your-redis-password-base64-encoded-here

---
# TLS Certificate Secret (for HTTPS)
# Create this using kubectl or cert-manager
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate
  namespace: plataforma-fastapi
  labels:
    app: plataforma-fastapi
    component: tls
type: kubernetes.io/tls
data:
  # TLS certificate and key (base64 encoded)
  # tls.crt: your-certificate-base64-encoded-here
  # tls.key: your-private-key-base64-encoded-here

---
# Example of how to create secrets using kubectl:
# 
# kubectl create secret generic fastapi-secrets \
#   --from-literal=SECRET_KEY='your-secret-key-here' \
#   --from-literal=JWT_SECRET_KEY='your-jwt-secret-key-here' \
#   --from-literal=SESSION_SECRET_KEY='your-session-secret-key-here' \
#   --from-literal=SUPABASE_URL='your-supabase-url-here' \
#   --from-literal=SUPABASE_ANON_KEY='your-supabase-anon-key-here' \
#   --from-literal=SUPABASE_SERVICE_KEY='your-supabase-service-key-here' \
#   --from-literal=SENTRY_DSN='your-sentry-dsn-here' \
#   --from-literal=GRAFANA_ADMIN_PASSWORD='your-grafana-password-here' \
#   --namespace=plataforma-fastapi
# 
# kubectl create secret generic postgres-secrets \
#   --from-literal=POSTGRES_PASSWORD='your-postgres-password-here' \
#   --from-literal=POSTGRES_REPLICATION_PASSWORD='your-replication-password-here' \
#   --namespace=plataforma-fastapi
# 
# kubectl create secret generic redis-secrets \
#   --from-literal=REDIS_PASSWORD='your-redis-password-here' \
#   --namespace=plataforma-fastapi
# 
# kubectl create secret tls tls-certificate \
#   --cert=path/to/tls.crt \
#   --key=path/to/tls.key \
#   --namespace=plataforma-fastapi