apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: plataforma-base

namespace: plataforma

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml
  - service-monitor.yaml

commonLabels:
  app: plataforma
  version: v1

images:
  - name: plataforma/backend
    newTag: latest
  - name: plataforma/frontend
    newTag: latest