apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: plataforma
  labels:
    app: plataforma
    component: redis
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      app: plataforma
      component: redis
  template:
    metadata:
      labels:
        app: plataforma
        component: redis
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      containers:
      - name: redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - /etc/redis/redis.conf
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: plataforma-secrets
              key: REDIS_PASSWORD
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - --no-auth-warning
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 20
          periodSeconds: 3
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - --no-auth-warning
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 20
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      labels:
        app: plataforma
        component: redis
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "fast-ssd"
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: plataforma
  labels:
    app: plataforma
    component: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: plataforma
    component: redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: plataforma
  labels:
    app: plataforma
    component: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: plataforma
    component: redis

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: plataforma
  labels:
    app: plataforma
    component: redis
data:
  redis.conf: |
    # Redis configuration for production
    
    # Network
    bind 0.0.0.0
    port 6379
    timeout 0
    
    # General
    daemonize no
    supervised no
    loglevel notice
    databases 16
    
    # Security
    requirepass changeme-redis-password
    
    # Memory management
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    
    # Persistence
    appendonly yes
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    
    # Save snapshots
    save 900 1
    save 300 10
    save 60 10000
    
    # Performance
    tcp-keepalive 300
    tcp-backlog 511
    
    # Clients
    maxclients 10000